config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'services', to: 'pages#services' 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

 def home
 end
 def services 
 end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AlphaBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="front-cover">
<div class="hero-text-box">
            <h1>A good idea can make all the difference.</h1>
            <h4>  Drive improvements of Healthcare by crowdsourcing ideas.</h4>
        </div>
    
    </div>
<section class="section-intro">
    <div class="row">
        <h2>BETTER HEALTHCARE MATTERS</h2>
        <p class="long-copy">We care deeply about those fighting disease having the best possible conditions to survive and live a life free from suffering. To improve healthcare there needs to be efficient ways for how to drive improvements. We believe that the key to successful improvements in healthcare is empowering the patients and healthcare staff to drive the change. We believe that the most important information for the improvement efforts of healthcare is ideas about how to do it. Brainhubs ambition is to be the best craftsmen of digital tools that crowdsource ideas, empower stakeholders and simplify modern management.</p>
    </div>
</section>
<section class="section-flow">
    <div class="row">
        <div class="col span-1-of-3 content">
            <h3>ENGAGE</h3>
            <br/><p><em>People</em></p></div>
        <div class="col span-1-of-3 content">
            <h3>CROWDSOURCE</h3>
            <br/><p><em>Ideas</em> </p></div>
        <div class="col span-1-of-3 content">
            <h3>IMPROVE</h3>
            <br/><p><em>Healthcare</em></p></div>
    </div>
    <div class="row">
        <div class="col span-1-of-3"> <img src="{% asset_path engagerowd2 %}" alt="Engage People" class="picture-flow" /> </div>
        <div class="col span-1-of-3"> <img src="{% asset_path crowdsource-cloud %}" alt="Health care Ideas" class="picture-flow" /> </div>
        <div class="col span-1-of-3"> <img src="{% asset_path improvehealthcare2fall2016 %}" alt="Improve HealthCare" class="picture-flow" /> </div>
    </div>
</section>

<%= link_to 'Services', services_path %>

app/views/pages/services.html.erb
<div class="about-cover">
</div>
<section class="section-about">
    <div class="row">
            <h2>BETTER HEALTHCARE MATTERS</h2>
            <p class="long-copy">Every person in need of healthcare deserves great healthcare. Our ambition is to build tools that drive improvements of healthcare and by doing that save peoples lives. We go in with all our heart in our work. Brainhubs is a swedish startup that was founded on the belief that the key to improve anything is ideas about how to do it. We all had our lives majorly affected by diseases in our families and now we want to make a difference for those in need of better healthcare. We combine our passion for better healthcare with modern management research and the opportunities that come with software.</p>
        <br/>
            <p class="long-copy">We pledge allegiance to those fighting against disease. We see ourselves as soldiers enlisted in the war for better healthcare and have set out on a journey to improve healthcare around the world. Our role in the war for better healthcare is as the weaponsmiths crafting tools that empower patients and healthcare staff to be the drivers of change. We will never give up the fight for better healthcare.</p>
        </div>
</section>

<%= link_to 'Home', root_path %>